name: 'Setup'
description: 'Setup Node.js and pnpm (via Corepack)'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22.21.0'

  pnpm-version:
    description: 'pnpm version'
    required: false
    default: 'pnpm@10.19.0+sha512.c9fc7236e92adf5c8af42fd5bf1612df99c2ceb62f27047032f4720b33f8eacdde311865e91c411f2774f618d82f320808ecb51718bfa82c060c4ba7c76a32b8'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true
        cache: pnpm

    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Prepare Corepack (from packageManager)
      shell: bash
      run: corepack install

    - name: Show versions
      shell: bash
      run: |
        node -v
        pnpm -v

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
