name: 'Setup'
description: 'Setup Node.js and pnpm (via Corepack)'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22.21.0'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true
        cache: pnpm

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Show versions
      shell: bash
      run: |
        node -v
        pnpm -v

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
