name: Deploy API (Production)

on:
  workflow_dispatch:

env:
  NODE_VERSION: '22.21.0'
  PNPM_VERSION: '10.19.0'
  BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            printf '%s' "${{ env.BETTER_AUTH_SECRET }}" | npx wrangler secret put BETTER_AUTH_SECRET --env production
            printf '%s' "${{ env.SECRET_KEY }}" | npx wrangler secret put SECRET_KEY --env production
          command: deploy --env=production
          workingDirectory: "apps/backend"